-- ADD OFFER PRICE TO PRODUCTS AND VARIANTS FOR STOREFRONT
ALTER TABLE products ADD COLUMN IF NOT EXISTS offer_price DECIMAL(12,2) DEFAULT NULL;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS offer_price DECIMAL(12,2) DEFAULT NULL;
